config/routes.rb
Rails.application.routes.draw do
  resources :quotes
  get 'friends/index'
  get 'users/profile'
  devise_for :users, controllers:{
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  get '/u/:id', to: 'users#profile', as: 'user'
#The following code bellow will redirect to something like this /post/1/comments/4
  resources :posts do
    resources :comments
  end
  get 'about', to: 'pages#about'
  get '/search', to: 'posts#search'


  root "pages#home"
  devise_scope :user do 
    get '/users/sign_out' => 'devise/sessions#destroy' 
  end
end

app/models/quote.rb
class Quote < ApplicationRecord
  validates :name, presence: true

  scope :ordered, -> { order(id: :desc) }
  # after_create_commit lambda {
  #   broadcast_prepend_to 'quotes', partial: 'quotes/quote', locals: { quote: self }, target: 'quotes'
  # }
  # # after_create_commit -> { broadcast_prepend_to 'quotes' }
  # after_update_commit -> { broadcast_replace_to 'quotes' }
  # after_destroy_commit -> { broadcast_remove_to 'quotes' }

  # # Using ActiveJob to improve performance
  # after_create_commit -> { broadcast_prepend_later_to "quotes" }
  # after_update_commit -> { broadcast_replace_later_to "quotes" }
  # after_destroy_commit -> { broadcast_remove_to "quotes" }

  #The three callbacks are equivalent to a single line of code
  broadcasts_to ->(quote) { "quotes" }, inserts_by: :prepend
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :set_quote, only: %i[ show edit update destroy ]

  # GET /quotes or /quotes.json
  def index
    @quotes = Quote.ordered
  end

  # GET /quotes/1 or /quotes/1.json
  def show
  end

  # GET /quotes/new
  def new
    @quote = Quote.new
  end

  # GET /quotes/1/edit
  def edit
  end

  # POST /quotes or /quotes.json
  def create
    @quote = Quote.new(quote_params)

    respond_to do |format|
      if @quote.save
        format.html { redirect_to quotes_url, notice: "Quote was successfully created." }
        format.json { render :show, status: :created, location: @quote }
        format.turbo_stream
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quotes/1 or /quotes/1.json
  def update
    respond_to do |format|
      if @quote.update(quote_params)
        format.html { redirect_to quote_url(@quote), notice: "Quote was successfully updated." }
        format.json { render :show, status: :ok, location: @quote }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quotes/1 or /quotes/1.json
  def destroy
    @quote.destroy

    respond_to do |format|
      format.html { redirect_to quotes_url, notice: 'Quote was successfully destroyed.' }
      format.json { head :no_content }
      # format.turbo_stream { render turbo_stream: turbo_stream.remove(@quote) }
      format.turbo_stream
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_quote
    @quote = Quote.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def quote_params
    params.require(:quote).permit(:name)
  end
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/quotes/_form.html.erb
<%= form_with(model: quote, class: "contents") do |form| %>
  <% if quote.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(quote.errors.count, "error") %> prohibited this quote from being saved:</h2>

      <ul>
        <% quote.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
    <%= link_to "Cancel", quotes_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
<% end %>

app/views/quotes/_quote.html.erb
<%= turbo_frame_tag quote do %>
<div id="<%= dom_id quote %>">
  <p class="my-5">
    <%= link_to quote.name, quote_path(quote), data:{turbo_frame: "_top"} %>
  </p>
  <%= link_to 'Edit', edit_quote_path(quote), class: "rounded-lg py-2 ml-2 px-2 bg-gray-100 inline-block font-medium" %>
  <%= button_to 'Delete', quote_path(quote), method: :delete, form:{data:{turbo_frame: "_top"}}, class: "rounded-lg py-2 ml-2 px-2 bg-gray-100 inline-block font-medium" %>
</div>
  <% end %>

app/views/quotes/create.turbo_stream.erb
<%= turbo_stream.prepend "quotes", partial: "quotes/quote", locals: { quote: @quote } %>
<%= turbo_stream.update Quote.new, "" %>

app/views/quotes/destroy.turbo_stream.erb
<%= turbo_stream.remove(@quote) %>

app/views/quotes/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing quote</h1>
<%= turbo_frame_tag @quote do %>
  <%= render "form", quote: @quote %>
<%end%>
  <%= link_to "Show this quote", @quote, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to quotes", quotes_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/quotes/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Quotes</h1>
    <%= link_to 'New quote', new_quote_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium", data:{turbo_frame:dom_id(Quote.new)} %>
  </div>

  <%= turbo_frame_tag Quote.new %>

 <%= turbo_frame_tag "quotes" do %>
    <%= render @quotes %>
  <% end %>
</div>

app/views/quotes/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New quote</h1>
  <%= turbo_frame_tag @quote do%>
    <%= render "form", quote: @quote %>
  <%end%>
  <%= link_to 'Back to quotes', quotes_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/quotes/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @quote %>

    <%= link_to 'Edit this quote', edit_quote_path(@quote), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this quote', quote_path(@quote), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to quotes', quotes_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>