config/routes.rb
Rails.application.routes.draw do
  resources :quotes
  get 'friends/index'
  get 'users/profile'
  devise_for :users, controllers:{
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  get '/u/:id', to: 'users#profile', as: 'user'
#The following code bellow will redirect to something like this /post/1/comments/4
  resources :posts do
    resources :comments
  end
  get 'about', to: 'pages#about'
  get '/search', to: 'posts#search'


  root "pages#home"
  devise_scope :user do 
    get '/users/sign_out' => 'devise/sessions#destroy' 
  end
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true, length: { minimum: 5, maximum: 50 }
  validates :body, presence: true, length: { minimum: 10, maximum: 5000 }

  belongs_to :user
  has_one_attached :image
  has_rich_text :body
  has_many :comments, dependent: :destroy
  has_noticed_notifications model_name: 'Notification'
  # has_many :notifications, through: :user, dependent: :destroy
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: %i[show index]

  # GET /posts or /posts.json
  def index
    @posts = Post.all.order(created_at: :desc)
  end

  # GET /posts/1 or /posts/1.json
  def show
    @post.update(views: @post.views + 1) unless current_user == @post.user
    @comments = @post.comments.order(created_at: :desc)
    mark_notification_as_read
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit; end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def search
    if params[:search].blank?
      redirect_to(posts_path, alert: 'Empty field!') and return
    else
      @parameter = params[:search].downcase
      @results = Post.all.where('lower(title) LIKE :search', search: "%#{@parameter}%")
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(:title, :body, :image)
  end

  def mark_notification_as_read
    return unless current_user

    notifications_to_mark_as_read = @post.notifications_as_post.where(recipient: current_user)
    # notifications_to_mark_as_read.update_all(read_at: Time.zone.now)
    notifications_to_mark_as_read.find_each do |notification|
      notification.update(read_at: Time.zone.now)
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post, class: "lg:max-w-5xl mx-auto") do |form| %>
  <% if post.errors.any? %>
    <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative" role="alert">
      <h2 class="font-bold mb-2"><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul class="list-disc ml-4">
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="mb-4">
    <%= form.label :title, class: "block text-gray-700 font-bold mb-2" %>
    <%= form.text_field :title, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
    <% post.errors.full_messages_for(:title).each do |message| %>
      <span class="block text-red-700 text-sm mt-1"><%= message %></span>
    <% end %>
  </div>

  <div class="mb-4">
    <%= form.label :body, class: "block text-gray-700 font-bold mb-2" %>
    <%= form.rich_text_area :body, class: "shadow appearance-none border rounded w-full min-h-60 py-2 px-3 text-gray-700 focus:outline-none focus:shadow-outline" %>
    <% post.errors.full_messages_for(:body).each do |message| %>
      <span class="block text-red-700 text-sm mt-1"><%= message %></span>
    <% end %>
  </div>

  <div class="mb-4">
    <%= form.label :image, class: "block text-gray-700 font-bold mb-2" %>
    <%= form.file_field :image, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
  </div>

  <div>
    <%= form.submit class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<!--Card 1-->

<div class="rounded overflow-hidden shadow-lg max-w-sm max-h-65 " id="<%= dom_id post %>">
    <% if post.image.attached? %>
      <%= image_tag post.image, class:"w-full max-h-20" %> 
    <% else %>
    <img src="https://mdbcdn.b-cdn.net/img/new/standard/nature/111.webp" class="w-full max-h-20"/>
    <% end %>
  <div class="px-6 py-1">
    <div class="font-bold text-xl mb-2"><%= post.title %></div>
    <p class="text-gray-700 text-sm">
        <% post_body_words = post.body.to_plain_text.split(' ') %>
        <% truncated_body = post_body_words[0..15].join(' ') %>
        <%= truncated_body %>.....
        <% if post_body_words.size > 20 %>
          <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">
            <%= link_to "Read More", post, class:"no-underline" %>
          </span>
        <% else %>
          <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">
            <%= link_to "Read More", post, class:"no-underline" %>
          </span>
        <% end %>
    </p>
  </div>
  <div class="px-6 pb-2 flex flex-row justify-center items-center">
      <span class="inline-block px-1 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">

          <% if post.user && post.user.image.attached? %>
              <%= image_tag post.user.image, class:"h-10 w-10 rounded-full bg-gray-50" %> 
          <% else %>
            <img src="https://mdbcdn.b-cdn.net/img/new/standard/nature/111.webp" class="h-10 w-10 rounded-full bg-gray-50"/>
          <% end %>
          </span>
    <span class="inline-block px-1 py-1 text-sm font-semibold text-gray-700 mr-2 ">Author: <%= link_to post.user.name, user_path(post.user), class:"no-underline" %></span>
    <span class="inline-block px-1 py-1 text-sm font-semibold text-gray-700 mr-2"> <%= pluralize( post.views, "views")%></span>
  </div>
</div>

app/views/posts/edit.html.erb
<section class="m-5">

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

</section>

app/views/posts/index.html.erb
  <section class="flex flex-col justify-content-center m-6">
    <div class="w-full">
      <%= render "shared/search" %>
    </div>
    <div data-controller="post-sort" class="w-50 d-flex justify-content-center m-auto">
      <label for="sort_by" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Articles</label>
      <select name="sort_by" id="sort_by" data-action="post-sort#update" data-post-sort-target="select" class="block w-full p-2 mb-6 text-sm text-gray-900 border border-gray-300 rounded-lg bg-gray-50 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500">
        <option value="time_posted" <% "selected" if params[:sort_by]=="time_posted" %>>Newest Articles</option>
        <option value="time_posted_reverse" <% "selected" if params[:sort_by]=="time_posted_reverse" %>>Oldest Articles</option>
      </select>
    </div>
    <div id="posts" class="p-10 flex justify-center">
      <div class="grid grid-cols-1 sm:grid-cols-1 md:grid-cols-3 lg:grid-cols-2 xl:grid-cols-2 gap-5">
        <% @posts.each do |post| %>
          <%= render post %>
        <% end %>
      </div>
    </div>
  </section>
</div>

app/views/posts/new.html.erb
<div class="container m-8">
  <div class="m-4">
    <%= link_to "Back to posts", posts_path, class: "btn btn-primary" %>
  </div>
  <%= render "form", post: @post %>
  <br>
</div>

app/views/posts/search.html.erb
<div class="container">
  <h1 class="my-5">Search Results</h1>

  <% if @results.any? %>
    <ul class="list-group">
      <% @results.each do |result| %>
        <li class="list-group-item">
          <%= link_to result.title, result %>
        </li>
      <% end %>
    </ul>
  <% else %>
    <p>No results found for your search query.</p>
  <% end %>
</div>

app/views/posts/show.html.erb
<div class= "container">
 <div class="mt-2">
    <%= link_to "Back", posts_path , class:" mx-3 p-2" %>
</div>  
  <div class="container px-4 px-lg-3 my-2"">
  <div id="<%= dom_id @post %>" class="row gx-4 gx-lg-5 align-items-center"  data-mdb-ripple-color="light">
    <a href="#!">
      <div class="mask" style="background-color: rgba(251, 251, 251, 0.15);"></div>
    </a>
  </div>
  <div class="card-body">
    <h2 class="card-title"><%= @post.title %></h2>
    <h4> Author: <%= link_to @post.user.name, user_path(@post.user), class:"no-underline text-black text-3xl" %>
    <h6> <%= pluralize( @post.views, "views")%></h6>
     <p class="card-text"><%= @post.body %></p>
  </div>
  <div class="me-auto ">
      <% if current_user==@post.user %>
      <div class="flex gap-2 justify-end">
        <%= link_to "Edit", edit_post_path(@post), class:"btn btn-primary p-2"  %>
        <%= button_to "Delete", @post, method: :delete, class:"btn btn-danger p-2"  %>
      </div>
      <% end %>
  </div>
</div>
</div>

<div class= "container ">
  <%= render "comments/form", post: @post, comment: @post.comments.build, submit_label:"Comment"  %>
  <% @comments.each do |comment| %>
    <%= render "comments/comment", post: @post, comment: comment %>
  <% end %>
</div>